<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.BlockData</code>
 */
class BlockData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.Vec3i relativePosition = 1;</code>
     */
    protected $relativePosition = null;
    /**
     *registered in BlockFeatureRegistry
     *
     * Generated from protobuf field <code>string feature = 2;</code>
     */
    protected $feature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\Vec3i $relativePosition
     *     @type string $feature
     *          registered in BlockFeatureRegistry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.Vec3i relativePosition = 1;</code>
     * @return \prokits\xyron\Vec3i|null
     */
    public function getRelativePosition()
    {
        return $this->relativePosition;
    }

    public function hasRelativePosition()
    {
        return isset($this->relativePosition);
    }

    public function clearRelativePosition()
    {
        unset($this->relativePosition);
    }

    /**
     * Generated from protobuf field <code>.xchange.Vec3i relativePosition = 1;</code>
     * @param \prokits\xyron\Vec3i $var
     * @return $this
     */
    public function setRelativePosition($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\Vec3i::class);
        $this->relativePosition = $var;

        return $this;
    }

    /**
     *registered in BlockFeatureRegistry
     *
     * Generated from protobuf field <code>string feature = 2;</code>
     * @return string
     */
    public function getFeature()
    {
        return $this->feature;
    }

    /**
     *registered in BlockFeatureRegistry
     *
     * Generated from protobuf field <code>string feature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->feature = $var;

        return $this;
    }

}

