<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use UnexpectedValueException;

/**
 * Protobuf type <code>xchange.DamageCause</code>
 */
class DamageCause
{
    /**
     * Generated from protobuf enum <code>Contact = 0;</code>
     */
    const Contact = 0;
    /**
     * Generated from protobuf enum <code>EntityAttack = 1;</code>
     */
    const EntityAttack = 1;
    /**
     * Generated from protobuf enum <code>Projectile = 2;</code>
     */
    const Projectile = 2;
    /**
     * Generated from protobuf enum <code>Suffocation = 3;</code>
     */
    const Suffocation = 3;
    /**
     * Generated from protobuf enum <code>Fall = 4;</code>
     */
    const Fall = 4;
    /**
     * Generated from protobuf enum <code>Fire = 5;</code>
     */
    const Fire = 5;
    /**
     * Generated from protobuf enum <code>FireTick = 6;</code>
     */
    const FireTick = 6;
    /**
     * Generated from protobuf enum <code>Lava = 7;</code>
     */
    const Lava = 7;
    /**
     * Generated from protobuf enum <code>Drowning = 8;</code>
     */
    const Drowning = 8;
    /**
     * Generated from protobuf enum <code>BlockExplosion = 9;</code>
     */
    const BlockExplosion = 9;
    /**
     * Generated from protobuf enum <code>EntityExplosion = 10;</code>
     */
    const EntityExplosion = 10;
    /**
     * Generated from protobuf enum <code>Void = 11;</code>
     */
    const Void = 11;
    /**
     * Generated from protobuf enum <code>Suicide = 12;</code>
     */
    const Suicide = 12;
    /**
     * Generated from protobuf enum <code>Magic = 13;</code>
     */
    const Magic = 13;
    /**
     * Generated from protobuf enum <code>Custom = 14;</code>
     */
    const Custom = 14;
    /**
     * Generated from protobuf enum <code>Starvation = 15;</code>
     */
    const Starvation = 15;
    /**
     * Generated from protobuf enum <code>FallingBlock = 16;</code>
     */
    const FallingBlock = 16;

    private static $valueToName = [
        self::Contact => 'Contact',
        self::EntityAttack => 'EntityAttack',
        self::Projectile => 'Projectile',
        self::Suffocation => 'Suffocation',
        self::Fall => 'Fall',
        self::Fire => 'Fire',
        self::FireTick => 'FireTick',
        self::Lava => 'Lava',
        self::Drowning => 'Drowning',
        self::BlockExplosion => 'BlockExplosion',
        self::EntityExplosion => 'EntityExplosion',
        self::Void => 'Void',
        self::Suicide => 'Suicide',
        self::Magic => 'Magic',
        self::Custom => 'Custom',
        self::Starvation => 'Starvation',
        self::FallingBlock => 'FallingBlock',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

