<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.EffectFeature</code>
 */
class EffectFeature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 amplifier = 1;</code>
     */
    protected $amplifier = 0;
    /**
     * Generated from protobuf field <code>bool isSpeed = 2;</code>
     */
    protected $isSpeed = false;
    /**
     * Generated from protobuf field <code>bool isHaste = 3;</code>
     */
    protected $isHaste = false;
    /**
     * Generated from protobuf field <code>bool isSlowFalling = 4;</code>
     */
    protected $isSlowFalling = false;
    /**
     * Generated from protobuf field <code>bool isLevitation = 5;</code>
     */
    protected $isLevitation = false;
    /**
     * Generated from protobuf field <code>bool isSlowness = 6;</code>
     */
    protected $isSlowness = false;
    /**
     * Generated from protobuf field <code>bool isJumpBoost = 7;</code>
     */
    protected $isJumpBoost = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $amplifier
     *     @type bool $isSpeed
     *     @type bool $isHaste
     *     @type bool $isSlowFalling
     *     @type bool $isLevitation
     *     @type bool $isSlowness
     *     @type bool $isJumpBoost
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 amplifier = 1;</code>
     * @return int
     */
    public function getAmplifier()
    {
        return $this->amplifier;
    }

    /**
     * Generated from protobuf field <code>int32 amplifier = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAmplifier($var)
    {
        GPBUtil::checkInt32($var);
        $this->amplifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSpeed = 2;</code>
     * @return bool
     */
    public function getIsSpeed()
    {
        return $this->isSpeed;
    }

    /**
     * Generated from protobuf field <code>bool isSpeed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSpeed($var)
    {
        GPBUtil::checkBool($var);
        $this->isSpeed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isHaste = 3;</code>
     * @return bool
     */
    public function getIsHaste()
    {
        return $this->isHaste;
    }

    /**
     * Generated from protobuf field <code>bool isHaste = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHaste($var)
    {
        GPBUtil::checkBool($var);
        $this->isHaste = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSlowFalling = 4;</code>
     * @return bool
     */
    public function getIsSlowFalling()
    {
        return $this->isSlowFalling;
    }

    /**
     * Generated from protobuf field <code>bool isSlowFalling = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSlowFalling($var)
    {
        GPBUtil::checkBool($var);
        $this->isSlowFalling = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isLevitation = 5;</code>
     * @return bool
     */
    public function getIsLevitation()
    {
        return $this->isLevitation;
    }

    /**
     * Generated from protobuf field <code>bool isLevitation = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLevitation($var)
    {
        GPBUtil::checkBool($var);
        $this->isLevitation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSlowness = 6;</code>
     * @return bool
     */
    public function getIsSlowness()
    {
        return $this->isSlowness;
    }

    /**
     * Generated from protobuf field <code>bool isSlowness = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSlowness($var)
    {
        GPBUtil::checkBool($var);
        $this->isSlowness = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isJumpBoost = 7;</code>
     * @return bool
     */
    public function getIsJumpBoost()
    {
        return $this->isJumpBoost;
    }

    /**
     * Generated from protobuf field <code>bool isJumpBoost = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsJumpBoost($var)
    {
        GPBUtil::checkBool($var);
        $this->isJumpBoost = $var;

        return $this;
    }

}

