<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.EntityPositionData</code>
 */
class EntityPositionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.Loc3f location = 1;</code>
     */
    protected $location = null;
    /**
     * Generated from protobuf field <code>.xchange.AxisAlignedBoundingBox boundingBox = 2;</code>
     */
    protected $boundingBox = null;
    /**
     * Generated from protobuf field <code>.xchange.BlockData below = 3;</code>
     */
    protected $below = null;
    /**
     * Generated from protobuf field <code>bool isImmobile = 4;</code>
     */
    protected $isImmobile = false;
    /**
     * Generated from protobuf field <code>bool isOnGround = 5;</code>
     */
    protected $isOnGround = false;
    /**
     * Generated from protobuf field <code>bool allowFlying = 6;</code>
     */
    protected $allowFlying = false;
    /**
     * Generated from protobuf field <code>bool isFlying = 7;</code>
     */
    protected $isFlying = false;
    /**
     * Generated from protobuf field <code>repeated .xchange.BlockData collidedBlocks = 8;</code>
     */
    private $collidedBlocks;
    /**
     * Generated from protobuf field <code>repeated .xchange.BlockData intersectedBlocks = 9;</code>
     */
    private $intersectedBlocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\Loc3f $location
     *     @type \prokits\xyron\AxisAlignedBoundingBox $boundingBox
     *     @type \prokits\xyron\BlockData $below
     *     @type bool $isImmobile
     *     @type bool $isOnGround
     *     @type bool $allowFlying
     *     @type bool $isFlying
     *     @type array<\prokits\xyron\BlockData>|\Google\Protobuf\Internal\RepeatedField $collidedBlocks
     *     @type array<\prokits\xyron\BlockData>|\Google\Protobuf\Internal\RepeatedField $intersectedBlocks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Player::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.Loc3f location = 1;</code>
     * @return \prokits\xyron\Loc3f|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    public function hasLocation()
    {
        return isset($this->location);
    }

    public function clearLocation()
    {
        unset($this->location);
    }

    /**
     * Generated from protobuf field <code>.xchange.Loc3f location = 1;</code>
     * @param \prokits\xyron\Loc3f $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\Loc3f::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xchange.AxisAlignedBoundingBox boundingBox = 2;</code>
     * @return \prokits\xyron\AxisAlignedBoundingBox|null
     */
    public function getBoundingBox()
    {
        return $this->boundingBox;
    }

    public function hasBoundingBox()
    {
        return isset($this->boundingBox);
    }

    public function clearBoundingBox()
    {
        unset($this->boundingBox);
    }

    /**
     * Generated from protobuf field <code>.xchange.AxisAlignedBoundingBox boundingBox = 2;</code>
     * @param \prokits\xyron\AxisAlignedBoundingBox $var
     * @return $this
     */
    public function setBoundingBox($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\AxisAlignedBoundingBox::class);
        $this->boundingBox = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xchange.BlockData below = 3;</code>
     * @return \prokits\xyron\BlockData|null
     */
    public function getBelow()
    {
        return $this->below;
    }

    public function hasBelow()
    {
        return isset($this->below);
    }

    public function clearBelow()
    {
        unset($this->below);
    }

    /**
     * Generated from protobuf field <code>.xchange.BlockData below = 3;</code>
     * @param \prokits\xyron\BlockData $var
     * @return $this
     */
    public function setBelow($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\BlockData::class);
        $this->below = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isImmobile = 4;</code>
     * @return bool
     */
    public function getIsImmobile()
    {
        return $this->isImmobile;
    }

    /**
     * Generated from protobuf field <code>bool isImmobile = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsImmobile($var)
    {
        GPBUtil::checkBool($var);
        $this->isImmobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isOnGround = 5;</code>
     * @return bool
     */
    public function getIsOnGround()
    {
        return $this->isOnGround;
    }

    /**
     * Generated from protobuf field <code>bool isOnGround = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOnGround($var)
    {
        GPBUtil::checkBool($var);
        $this->isOnGround = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allowFlying = 6;</code>
     * @return bool
     */
    public function getAllowFlying()
    {
        return $this->allowFlying;
    }

    /**
     * Generated from protobuf field <code>bool allowFlying = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowFlying($var)
    {
        GPBUtil::checkBool($var);
        $this->allowFlying = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isFlying = 7;</code>
     * @return bool
     */
    public function getIsFlying()
    {
        return $this->isFlying;
    }

    /**
     * Generated from protobuf field <code>bool isFlying = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFlying($var)
    {
        GPBUtil::checkBool($var);
        $this->isFlying = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.BlockData collidedBlocks = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollidedBlocks()
    {
        return $this->collidedBlocks;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.BlockData collidedBlocks = 8;</code>
     * @param array<\prokits\xyron\BlockData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollidedBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\xyron\BlockData::class);
        $this->collidedBlocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.BlockData intersectedBlocks = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntersectedBlocks()
    {
        return $this->intersectedBlocks;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.BlockData intersectedBlocks = 9;</code>
     * @param array<\prokits\xyron\BlockData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntersectedBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\xyron\BlockData::class);
        $this->intersectedBlocks = $arr;

        return $this;
    }

}

