<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.ItemData</code>
 */
class ItemData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>string vanillaName = 2;</code>
     */
    protected $vanillaName = '';
    /**
     *string feature = 3; //registered in ItemFeatureRegistry
     *
     * Generated from protobuf field <code>.xchange.ItemFeature feature = 3;</code>
     */
    protected $feature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $count
     *     @type string $vanillaName
     *     @type \prokits\xyron\ItemFeature $feature
     *          string feature = 3; //registered in ItemFeatureRegistry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vanillaName = 2;</code>
     * @return string
     */
    public function getVanillaName()
    {
        return $this->vanillaName;
    }

    /**
     * Generated from protobuf field <code>string vanillaName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVanillaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->vanillaName = $var;

        return $this;
    }

    /**
     *string feature = 3; //registered in ItemFeatureRegistry
     *
     * Generated from protobuf field <code>.xchange.ItemFeature feature = 3;</code>
     * @return \prokits\xyron\ItemFeature|null
     */
    public function getFeature()
    {
        return $this->feature;
    }

    public function hasFeature()
    {
        return isset($this->feature);
    }

    public function clearFeature()
    {
        unset($this->feature);
    }

    /**
     *string feature = 3; //registered in ItemFeatureRegistry
     *
     * Generated from protobuf field <code>.xchange.ItemFeature feature = 3;</code>
     * @param \prokits\xyron\ItemFeature $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\ItemFeature::class);
        $this->feature = $var;

        return $this;
    }

}

