<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.Player</code>
 */
class Player extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.DeviceOS os = 1;</code>
     */
    protected $os = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $os
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Player::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.DeviceOS os = 1;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * Generated from protobuf field <code>.xchange.DeviceOS os = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkEnum($var, \prokits\xyron\DeviceOS::class);
        $this->os = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

