<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xchange.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerReceipt</code>
 */
class PlayerReceipt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string internalId = 1;</code>
     */
    protected $internalId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $internalId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xchange::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string internalId = 1;</code>
     * @return string
     */
    public function getInternalId()
    {
        return $this->internalId;
    }

    /**
     * Generated from protobuf field <code>string internalId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInternalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->internalId = $var;

        return $this;
    }

}

