<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerGameModeData</code>
 */
class PlayerGameModeData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.GameMode gameMode = 1;</code>
     */
    protected $gameMode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $gameMode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.GameMode gameMode = 1;</code>
     * @return int
     */
    public function getGameMode()
    {
        return $this->gameMode;
    }

    /**
     * Generated from protobuf field <code>.xchange.GameMode gameMode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setGameMode($var)
    {
        GPBUtil::checkEnum($var, \prokits\xyron\GameMode::class);
        $this->gameMode = $var;

        return $this;
    }

}

