<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerInputModeData</code>
 */
class PlayerInputModeData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.InputMode inputMode = 1;</code>
     */
    protected $inputMode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $inputMode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.InputMode inputMode = 1;</code>
     * @return int
     */
    public function getInputMode()
    {
        return $this->inputMode;
    }

    /**
     * Generated from protobuf field <code>.xchange.InputMode inputMode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setInputMode($var)
    {
        GPBUtil::checkEnum($var, \prokits\xyron\InputMode::class);
        $this->inputMode = $var;

        return $this;
    }

}

