<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerHeldItemChangeData</code>
 */
class PlayerHeldItemChangeData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.ItemData item = 1;</code>
     */
    protected $item = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\ItemData $item
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.ItemData item = 1;</code>
     * @return \prokits\xyron\ItemData|null
     */
    public function getItem()
    {
        return $this->item;
    }

    public function hasItem()
    {
        return isset($this->item);
    }

    public function clearItem()
    {
        unset($this->item);
    }

    /**
     * Generated from protobuf field <code>.xchange.ItemData item = 1;</code>
     * @param \prokits\xyron\ItemData $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\ItemData::class);
        $this->item = $var;

        return $this;
    }

}

