<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerAddEffectData</code>
 */
class PlayerAddEffectData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.EffectFeature effect = 1;</code>
     */
    protected $effect = null;
    /**
     * Generated from protobuf field <code>string internalEffectId = 2;</code>
     */
    protected $internalEffectId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\EffectFeature $effect
     *     @type string $internalEffectId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.EffectFeature effect = 1;</code>
     * @return \prokits\xyron\EffectFeature|null
     */
    public function getEffect()
    {
        return $this->effect;
    }

    public function hasEffect()
    {
        return isset($this->effect);
    }

    public function clearEffect()
    {
        unset($this->effect);
    }

    /**
     * Generated from protobuf field <code>.xchange.EffectFeature effect = 1;</code>
     * @param \prokits\xyron\EffectFeature $var
     * @return $this
     */
    public function setEffect($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\EffectFeature::class);
        $this->effect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string internalEffectId = 2;</code>
     * @return string
     */
    public function getInternalEffectId()
    {
        return $this->internalEffectId;
    }

    /**
     * Generated from protobuf field <code>string internalEffectId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInternalEffectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->internalEffectId = $var;

        return $this;
    }

}

