<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *message BlockFeatureRegistry {
 *map<string, BlockFeature> features = 1;
 *}
 *
 * Generated from protobuf message <code>xchange.PotionEffectRegistry</code>
 */
class PotionEffectRegistry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string effects = 1;</code>
     */
    private $effects;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $effects
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string effects = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEffects()
    {
        return $this->effects;
    }

    /**
     * Generated from protobuf field <code>repeated string effects = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEffects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->effects = $arr;

        return $this;
    }

}

