<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xchange.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *TODO improve this
 *
 * Generated from protobuf message <code>xchange.ServerExecution</code>
 */
class ServerExecution extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string extraData = 2;</code>
     */
    protected $extraData = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $extraData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xchange::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extraData = 2;</code>
     * @return string
     */
    public function getExtraData()
    {
        return $this->extraData;
    }

    /**
     * Generated from protobuf field <code>string extraData = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExtraData($var)
    {
        GPBUtil::checkString($var, True);
        $this->extraData = $var;

        return $this;
    }

}

