<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.Vec3f</code>
 */
class Vec3f extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float x = 1;</code>
     */
    protected $x = 0.0;
    /**
     * Generated from protobuf field <code>float y = 2;</code>
     */
    protected $y = 0.0;
    /**
     * Generated from protobuf field <code>float z = 3;</code>
     */
    protected $z = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $x
     *     @type float $y
     *     @type float $z
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float x = 1;</code>
     * @return float
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Generated from protobuf field <code>float x = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setX($var)
    {
        GPBUtil::checkFloat($var);
        $this->x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float y = 2;</code>
     * @return float
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>float y = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setY($var)
    {
        GPBUtil::checkFloat($var);
        $this->y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float z = 3;</code>
     * @return float
     */
    public function getZ()
    {
        return $this->z;
    }

    /**
     * Generated from protobuf field <code>float z = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setZ($var)
    {
        GPBUtil::checkFloat($var);
        $this->z = $var;

        return $this;
    }

}

