<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use UnexpectedValueException;

/**
 * Protobuf type <code>xchange.BreakBlockStatus</code>
 */
class BreakBlockStatus
{
    /**
     * Generated from protobuf enum <code>StartBreak = 0;</code>
     */
    const StartBreak = 0;
    /**
     * Generated from protobuf enum <code>AbortBreak = 1;</code>
     */
    const AbortBreak = 1;
    /**
     * Generated from protobuf enum <code>FinishBreak = 2;</code>
     */
    const FinishBreak = 2;

    private static $valueToName = [
        self::StartBreak => 'StartBreak',
        self::AbortBreak => 'AbortBreak',
        self::FinishBreak => 'FinishBreak',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

