<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use UnexpectedValueException;

/**
 * Protobuf type <code>xchange.GameMode</code>
 */
class GameMode
{
    /**
     * Generated from protobuf enum <code>Survival = 0;</code>
     */
    const Survival = 0;
    /**
     * Generated from protobuf enum <code>Creative = 1;</code>
     */
    const Creative = 1;
    /**
     * Generated from protobuf enum <code>Adventure = 2;</code>
     */
    const Adventure = 2;
    /**
     * Generated from protobuf enum <code>Spectator = 3;</code>
     */
    const Spectator = 3;

    private static $valueToName = [
        self::Survival => 'Survival',
        self::Creative => 'Creative',
        self::Adventure => 'Adventure',
        self::Spectator => 'Spectator',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

