<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.ItemFeature</code>
 */
class ItemFeature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isArmor = 1;</code>
     */
    protected $isArmor = false;
    /**
     * Generated from protobuf field <code>bool isBlockPlanterItem = 2;</code>
     */
    protected $isBlockPlanterItem = false;
    /**
     * Generated from protobuf field <code>bool isDamageable = 3;</code>
     */
    protected $isDamageable = false;
    /**
     * Generated from protobuf field <code>bool isFood = 4;</code>
     */
    protected $isFood = false;
    /**
     * Generated from protobuf field <code>bool isThrowable = 5;</code>
     */
    protected $isThrowable = false;
    /**
     * Generated from protobuf field <code>bool isTool = 6;</code>
     */
    protected $isTool = false;
    /**
     * Generated from protobuf field <code>bool isBow = 7;</code>
     */
    protected $isBow = false;
    /**
     * Generated from protobuf field <code>bool isCrossBow = 8;</code>
     */
    protected $isCrossBow = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isArmor
     *     @type bool $isBlockPlanterItem
     *     @type bool $isDamageable
     *     @type bool $isFood
     *     @type bool $isThrowable
     *     @type bool $isTool
     *     @type bool $isBow
     *     @type bool $isCrossBow
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isArmor = 1;</code>
     * @return bool
     */
    public function getIsArmor()
    {
        return $this->isArmor;
    }

    /**
     * Generated from protobuf field <code>bool isArmor = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsArmor($var)
    {
        GPBUtil::checkBool($var);
        $this->isArmor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isBlockPlanterItem = 2;</code>
     * @return bool
     */
    public function getIsBlockPlanterItem()
    {
        return $this->isBlockPlanterItem;
    }

    /**
     * Generated from protobuf field <code>bool isBlockPlanterItem = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBlockPlanterItem($var)
    {
        GPBUtil::checkBool($var);
        $this->isBlockPlanterItem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isDamageable = 3;</code>
     * @return bool
     */
    public function getIsDamageable()
    {
        return $this->isDamageable;
    }

    /**
     * Generated from protobuf field <code>bool isDamageable = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDamageable($var)
    {
        GPBUtil::checkBool($var);
        $this->isDamageable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isFood = 4;</code>
     * @return bool
     */
    public function getIsFood()
    {
        return $this->isFood;
    }

    /**
     * Generated from protobuf field <code>bool isFood = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFood($var)
    {
        GPBUtil::checkBool($var);
        $this->isFood = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isThrowable = 5;</code>
     * @return bool
     */
    public function getIsThrowable()
    {
        return $this->isThrowable;
    }

    /**
     * Generated from protobuf field <code>bool isThrowable = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsThrowable($var)
    {
        GPBUtil::checkBool($var);
        $this->isThrowable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isTool = 6;</code>
     * @return bool
     */
    public function getIsTool()
    {
        return $this->isTool;
    }

    /**
     * Generated from protobuf field <code>bool isTool = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTool($var)
    {
        GPBUtil::checkBool($var);
        $this->isTool = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isBow = 7;</code>
     * @return bool
     */
    public function getIsBow()
    {
        return $this->isBow;
    }

    /**
     * Generated from protobuf field <code>bool isBow = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBow($var)
    {
        GPBUtil::checkBool($var);
        $this->isBow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isCrossBow = 8;</code>
     * @return bool
     */
    public function getIsCrossBow()
    {
        return $this->isCrossBow;
    }

    /**
     * Generated from protobuf field <code>bool isCrossBow = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCrossBow($var)
    {
        GPBUtil::checkBool($var);
        $this->isCrossBow = $var;

        return $this;
    }

}

