<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerEffectData</code>
 */
class PlayerEffectData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xchange.EffectFeature effect = 1;</code>
     */
    private $effect;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\prokits\xyron\EffectFeature>|\Google\Protobuf\Internal\RepeatedField $effect
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.EffectFeature effect = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEffect()
    {
        return $this->effect;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.EffectFeature effect = 1;</code>
     * @param array<\prokits\xyron\EffectFeature>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEffect($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\xyron\EffectFeature::class);
        $this->effect = $arr;

        return $this;
    }

}

