<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerMoveData</code>
 */
class PlayerMoveData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.EntityPositionData newPosition = 1;</code>
     */
    protected $newPosition = null;
    /**
     * Generated from protobuf field <code>bool teleport = 2;</code>
     */
    protected $teleport = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\EntityPositionData $newPosition
     *     @type bool $teleport
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.EntityPositionData newPosition = 1;</code>
     * @return \prokits\xyron\EntityPositionData|null
     */
    public function getNewPosition()
    {
        return $this->newPosition;
    }

    public function hasNewPosition()
    {
        return isset($this->newPosition);
    }

    public function clearNewPosition()
    {
        unset($this->newPosition);
    }

    /**
     * Generated from protobuf field <code>.xchange.EntityPositionData newPosition = 1;</code>
     * @param \prokits\xyron\EntityPositionData $var
     * @return $this
     */
    public function setNewPosition($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\EntityPositionData::class);
        $this->newPosition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool teleport = 2;</code>
     * @return bool
     */
    public function getTeleport()
    {
        return $this->teleport;
    }

    /**
     * Generated from protobuf field <code>bool teleport = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setTeleport($var)
    {
        GPBUtil::checkBool($var);
        $this->teleport = $var;

        return $this;
    }

}

