<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.AxisAlignedBoundingBox</code>
 */
class AxisAlignedBoundingBox extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.Vec3f min = 1;</code>
     */
    protected $min = null;
    /**
     * Generated from protobuf field <code>.xchange.Vec3f max = 2;</code>
     */
    protected $max = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\Vec3f $min
     *     @type \prokits\xyron\Vec3f $max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.Vec3f min = 1;</code>
     * @return \prokits\xyron\Vec3f|null
     */
    public function getMin()
    {
        return $this->min;
    }

    public function hasMin()
    {
        return isset($this->min);
    }

    public function clearMin()
    {
        unset($this->min);
    }

    /**
     * Generated from protobuf field <code>.xchange.Vec3f min = 1;</code>
     * @param \prokits\xyron\Vec3f $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\Vec3f::class);
        $this->min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xchange.Vec3f max = 2;</code>
     * @return \prokits\xyron\Vec3f|null
     */
    public function getMax()
    {
        return $this->max;
    }

    public function hasMax()
    {
        return isset($this->max);
    }

    public function clearMax()
    {
        unset($this->max);
    }

    /**
     * Generated from protobuf field <code>.xchange.Vec3f max = 2;</code>
     * @param \prokits\xyron\Vec3f $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\Vec3f::class);
        $this->max = $var;

        return $this;
    }

}

