<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xchange.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.BatchedReportResponseEntry</code>
 */
class BatchedReportResponseEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.PlayerReceipt player = 1;</code>
     */
    protected $player = null;
    /**
     * Generated from protobuf field <code>repeated .xchange.JudgementData judgements = 2;</code>
     */
    private $judgements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\PlayerReceipt $player
     *     @type array<\prokits\xyron\JudgementData>|\Google\Protobuf\Internal\RepeatedField $judgements
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xchange::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.PlayerReceipt player = 1;</code>
     * @return \prokits\xyron\PlayerReceipt|null
     */
    public function getPlayer()
    {
        return $this->player;
    }

    public function hasPlayer()
    {
        return isset($this->player);
    }

    public function clearPlayer()
    {
        unset($this->player);
    }

    /**
     * Generated from protobuf field <code>.xchange.PlayerReceipt player = 1;</code>
     * @param \prokits\xyron\PlayerReceipt $var
     * @return $this
     */
    public function setPlayer($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\PlayerReceipt::class);
        $this->player = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.JudgementData judgements = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJudgements()
    {
        return $this->judgements;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.JudgementData judgements = 2;</code>
     * @param array<\prokits\xyron\JudgementData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJudgements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\xyron\JudgementData::class);
        $this->judgements = $arr;

        return $this;
    }

}

