<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.BlockFeature</code>
 */
class BlockFeature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xchange.AxisAlignedBoundingBox collisionBoxes = 2;</code>
     */
    private $collisionBoxes;
    /**
     * Generated from protobuf field <code>float friction = 3;</code>
     */
    protected $friction = 0.0;
    /**
     * Generated from protobuf field <code>bool isSolid = 4;</code>
     */
    protected $isSolid = false;
    /**
     * Generated from protobuf field <code>bool isLiquid = 5;</code>
     */
    protected $isLiquid = false;
    /**
     * Generated from protobuf field <code>bool isAir = 6;</code>
     */
    protected $isAir = false;
    /**
     * Generated from protobuf field <code>bool isSlime = 7;</code>
     */
    protected $isSlime = false;
    /**
     * Generated from protobuf field <code>bool isClimbable = 8;</code>
     */
    protected $isClimbable = false;
    /**
     * Generated from protobuf field <code>bool isIce = 9;</code>
     */
    protected $isIce = false;
    /**
     * Generated from protobuf field <code>bool isCobweb = 10;</code>
     */
    protected $isCobweb = false;
    /**
     * Generated from protobuf field <code>bool isSweetBerry = 11;</code>
     */
    protected $isSweetBerry = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\prokits\xyron\AxisAlignedBoundingBox>|\Google\Protobuf\Internal\RepeatedField $collisionBoxes
     *     @type float $friction
     *     @type bool $isSolid
     *     @type bool $isLiquid
     *     @type bool $isAir
     *     @type bool $isSlime
     *     @type bool $isClimbable
     *     @type bool $isIce
     *     @type bool $isCobweb
     *     @type bool $isSweetBerry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PrimitiveTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.AxisAlignedBoundingBox collisionBoxes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollisionBoxes()
    {
        return $this->collisionBoxes;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.AxisAlignedBoundingBox collisionBoxes = 2;</code>
     * @param array<\prokits\xyron\AxisAlignedBoundingBox>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollisionBoxes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\xyron\AxisAlignedBoundingBox::class);
        $this->collisionBoxes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float friction = 3;</code>
     * @return float
     */
    public function getFriction()
    {
        return $this->friction;
    }

    /**
     * Generated from protobuf field <code>float friction = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setFriction($var)
    {
        GPBUtil::checkFloat($var);
        $this->friction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSolid = 4;</code>
     * @return bool
     */
    public function getIsSolid()
    {
        return $this->isSolid;
    }

    /**
     * Generated from protobuf field <code>bool isSolid = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSolid($var)
    {
        GPBUtil::checkBool($var);
        $this->isSolid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isLiquid = 5;</code>
     * @return bool
     */
    public function getIsLiquid()
    {
        return $this->isLiquid;
    }

    /**
     * Generated from protobuf field <code>bool isLiquid = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLiquid($var)
    {
        GPBUtil::checkBool($var);
        $this->isLiquid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isAir = 6;</code>
     * @return bool
     */
    public function getIsAir()
    {
        return $this->isAir;
    }

    /**
     * Generated from protobuf field <code>bool isAir = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAir($var)
    {
        GPBUtil::checkBool($var);
        $this->isAir = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSlime = 7;</code>
     * @return bool
     */
    public function getIsSlime()
    {
        return $this->isSlime;
    }

    /**
     * Generated from protobuf field <code>bool isSlime = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSlime($var)
    {
        GPBUtil::checkBool($var);
        $this->isSlime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isClimbable = 8;</code>
     * @return bool
     */
    public function getIsClimbable()
    {
        return $this->isClimbable;
    }

    /**
     * Generated from protobuf field <code>bool isClimbable = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsClimbable($var)
    {
        GPBUtil::checkBool($var);
        $this->isClimbable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isIce = 9;</code>
     * @return bool
     */
    public function getIsIce()
    {
        return $this->isIce;
    }

    /**
     * Generated from protobuf field <code>bool isIce = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsIce($var)
    {
        GPBUtil::checkBool($var);
        $this->isIce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isCobweb = 10;</code>
     * @return bool
     */
    public function getIsCobweb()
    {
        return $this->isCobweb;
    }

    /**
     * Generated from protobuf field <code>bool isCobweb = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCobweb($var)
    {
        GPBUtil::checkBool($var);
        $this->isCobweb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSweetBerry = 11;</code>
     * @return bool
     */
    public function getIsSweetBerry()
    {
        return $this->isSweetBerry;
    }

    /**
     * Generated from protobuf field <code>bool isSweetBerry = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSweetBerry($var)
    {
        GPBUtil::checkBool($var);
        $this->isSweetBerry = $var;

        return $this;
    }

}

