<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use UnexpectedValueException;

/**
 * Protobuf type <code>xchange.InputMode</code>
 */
class InputMode
{
    /**
     * Generated from protobuf enum <code>MouseKeyboard = 0;</code>
     */
    const MouseKeyboard = 0;
    /**
     * Generated from protobuf enum <code>Touch = 1;</code>
     */
    const Touch = 1;
    /**
     * Generated from protobuf enum <code>Gamepad = 2;</code>
     */
    const Gamepad = 2;
    /**
     * Generated from protobuf enum <code>MotionController = 3;</code>
     */
    const MotionController = 3;

    private static $valueToName = [
        self::MouseKeyboard => 'MouseKeyboard',
        self::Touch => 'Touch',
        self::Gamepad => 'Gamepad',
        self::MotionController => 'MotionController',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

