<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xchange.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.JudgementData</code>
 */
class JudgementData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>.xchange.Judgement judgement = 2;</code>
     */
    protected $judgement = 0;
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type int $judgement
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xchange::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xchange.Judgement judgement = 2;</code>
     * @return int
     */
    public function getJudgement()
    {
        return $this->judgement;
    }

    /**
     * Generated from protobuf field <code>.xchange.Judgement judgement = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setJudgement($var)
    {
        GPBUtil::checkEnum($var, \prokits\xyron\Judgement::class);
        $this->judgement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

