<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

namespace prokits\xyron;

use UnexpectedValueException;

/**
 * Protobuf type <code>xchange.PlayerAction</code>
 */
class PlayerAction
{
    /**
     * Generated from protobuf enum <code>Jump = 0;</code>
     */
    const Jump = 0;
    /**
     * Generated from protobuf enum <code>Swing = 1;</code>
     */
    const Swing = 1;
    /**
     * Generated from protobuf enum <code>StartSprint = 2;</code>
     */
    const StartSprint = 2;
    /**
     * Generated from protobuf enum <code>StopSprint = 3;</code>
     */
    const StopSprint = 3;
    /**
     * Generated from protobuf enum <code>StartSneak = 4;</code>
     */
    const StartSneak = 4;
    /**
     * Generated from protobuf enum <code>StopSneak = 5;</code>
     */
    const StopSneak = 5;
    /**
     * Generated from protobuf enum <code>StartSprintFlying = 6;</code>
     */
    const StartSprintFlying = 6;
    /**
     * Generated from protobuf enum <code>StopSprintFlying = 7;</code>
     */
    const StopSprintFlying = 7;
    /**
     * Generated from protobuf enum <code>StartGliding = 8;</code>
     */
    const StartGliding = 8;
    /**
     * Generated from protobuf enum <code>StopGliding = 9;</code>
     */
    const StopGliding = 9;
    /**
     * Generated from protobuf enum <code>StartSwimming = 10;</code>
     */
    const StartSwimming = 10;
    /**
     * Generated from protobuf enum <code>StopSwimming = 11;</code>
     */
    const StopSwimming = 11;
    /**
     * Generated from protobuf enum <code>OpenInventory = 12;</code>
     */
    const OpenInventory = 12;
    /**
     * Generated from protobuf enum <code>CloseInventory = 13;</code>
     */
    const CloseInventory = 13;

    private static $valueToName = [
        self::Jump => 'Jump',
        self::Swing => 'Swing',
        self::StartSprint => 'StartSprint',
        self::StopSprint => 'StopSprint',
        self::StartSneak => 'StartSneak',
        self::StopSneak => 'StopSneak',
        self::StartSprintFlying => 'StartSprintFlying',
        self::StopSprintFlying => 'StopSprintFlying',
        self::StartGliding => 'StartGliding',
        self::StopGliding => 'StopGliding',
        self::StartSwimming => 'StartSwimming',
        self::StopSwimming => 'StopSwimming',
        self::OpenInventory => 'OpenInventory',
        self::CloseInventory => 'CloseInventory',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

