<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_wrappers.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.PlayerAttackData</code>
 */
class PlayerAttackData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xchange.AttackData data = 1;</code>
     */
    protected $data = null;
    /**
     * Generated from protobuf field <code>bool damaged = 2;</code>
     */
    protected $damaged = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \prokits\xyron\AttackData $data
     *     @type bool $damaged
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlayerWrappers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xchange.AttackData data = 1;</code>
     * @return \prokits\xyron\AttackData|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.xchange.AttackData data = 1;</code>
     * @param \prokits\xyron\AttackData $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \prokits\xyron\AttackData::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool damaged = 2;</code>
     * @return bool
     */
    public function getDamaged()
    {
        return $this->damaged;
    }

    /**
     * Generated from protobuf field <code>bool damaged = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDamaged($var)
    {
        GPBUtil::checkBool($var);
        $this->damaged = $var;

        return $this;
    }

}

