<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xchange.proto

namespace prokits\xyron;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xchange.ReportResponse</code>
 */
class ReportResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xchange.JudgementData judgements = 1;</code>
     */
    private $judgements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\prokits\xyron\JudgementData>|\Google\Protobuf\Internal\RepeatedField $judgements
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xchange::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.JudgementData judgements = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJudgements()
    {
        return $this->judgements;
    }

    /**
     * Generated from protobuf field <code>repeated .xchange.JudgementData judgements = 1;</code>
     * @param array<\prokits\xyron\JudgementData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJudgements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\xyron\JudgementData::class);
        $this->judgements = $arr;

        return $this;
    }

}

