<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive_types.proto

namespace GPBMetadata;

class PrimitiveTypes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ë
primitive_types.protoxchange"
Vec2f	
x (	
y ("
Vec2i	
x (	
y ("(
Vec3f	
x (	
y (	
z ("(
Vec3i	
x (	
y (	
z ("L
Loc3f 
position (2.xchange.Vec3f!
	direction (2.xchange.Vec3f"R
AxisAlignedBoundingBox
min (2.xchange.Vec3f
max (2.xchange.Vec3f"]
	BlockData(
relativePosition (2.xchange.Vec3i&
feature (2.xchange.BlockFeature"¿
BlockFeature7
collisionBoxes (2.xchange.AxisAlignedBoundingBox
friction (
isSolid (
isLiquid (
isAir (
isSlime (
isClimbable (
isIce	 ("\'
PotionEffectRegistry
effects (	"U
ItemData
count (
vanillaName (	%
feature (2.xchange.ItemFeature"®
ItemFeature
isArmor (
isBlockPlanterItem (
isDamageable (
isFood (
isThrowable (
isTool (
isBow (

isCrossBow (B=
com.github.blackjack200.xyronZxyron/à prokits\\xyron–bproto3'
        , true);

        static::$is_initialized = true;
    }
}

