// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anticheat_types.proto

package com.github.blackjack200.xyron;

public final class AnticheatTypes {
  private AnticheatTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code xchange.Judgement}
   */
  public enum Judgement
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEBUG = 0;</code>
     */
    DEBUG(0),
    /**
     * <code>AMBIGUOUS = 1;</code>
     */
    AMBIGUOUS(1),
    /**
     * <code>TRIGGER = 2;</code>
     */
    TRIGGER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEBUG = 0;</code>
     */
    public static final int DEBUG_VALUE = 0;
    /**
     * <code>AMBIGUOUS = 1;</code>
     */
    public static final int AMBIGUOUS_VALUE = 1;
    /**
     * <code>TRIGGER = 2;</code>
     */
    public static final int TRIGGER_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Judgement valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Judgement forNumber(int value) {
      switch (value) {
        case 0: return DEBUG;
        case 1: return AMBIGUOUS;
        case 2: return TRIGGER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Judgement>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Judgement> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Judgement>() {
            public Judgement findValueByNumber(int number) {
              return Judgement.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.blackjack200.xyron.AnticheatTypes.getDescriptor().getEnumTypes().get(0);
    }

    private static final Judgement[] VALUES = values();

    public static Judgement valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Judgement(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xchange.Judgement)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025anticheat_types.proto\022\007xchange*2\n\tJudg" +
      "ement\022\t\n\005DEBUG\020\000\022\r\n\tAMBIGUOUS\020\001\022\013\n\007TRIGG" +
      "ER\020\002B=\n\035com.github.blackjack200.xyronZ\006x" +
      "yron/\210\001\001\312\002\rprokits\\xyron\320\002\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
